---

- name: Ensure pipx is installed
  ansible.builtin.package:
    name: pipx
    state: present

- name: Ensure pipx path is configured
  ansible.builtin.command: pipx ensurepath
  changed_when: false

- name: Install ansible-dev-tools using pipx
  community.general.pipx:
    name: ansible-dev-tools
    state: present