---
- name: Set shell to {{ root_shell }} for root
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: '/bin/{{ root_shell }}'
  tags:
    - shell

- name: Set shell to {{ user_shell }} for {{ current_user }}
  become: true
  ansible.builtin.user:
    name: "{{ current_user }}"
    shell: '/usr/bin/{{ user_shell }}'
  tags:
    - shell